# helperapp/tests/extract_decomp.py
#
# Copies function, table and #define definitions out of the decomp's own
# sources verbatim, for tests/decomp_reference.c -- the differential test
# that runs the *original* battle code side by side with the port in
# calc/src/ (see that file's header comment). Run by tests/CMakeLists.txt at
# build time; never hand-edit its output.
#
#   python3 extract_decomp.py <repo root> <output file> <file>:<name> ...
#
# <name> is a function, a (static) const table, or a #define macro; each is
# found by its definition at the start of a line and copied whole (braces
# matched for functions/tables, backslash continuations for macros).
import re
import sys


def extract(text, name, path):
    # #define NAME ... (with continuation lines)
    m = re.search(rf"^#define {re.escape(name)}\b.*?(?<!\\)$", text, re.MULTILINE | re.DOTALL)
    if m:
        return m.group(0)

    # A definition: something at column 0 naming `name` followed by ( or [,
    # and a body in braces (not a prototype ending in ';').
    for m in re.finditer(rf"^[A-Za-z_][^\n;{{}}]*\b{re.escape(name)}\s*[(\[][^;{{]*?\{{", text, re.MULTILINE):
        start = m.start()
        i = m.end()
        depth = 1
        while depth:
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            i += 1
        # tables end with "};", functions with "}"
        if text[i:i + 1] == ";":
            i += 1
        return text[start:i]
    raise SystemExit(f"extract_decomp.py: {name} not found in {path}")


def main():
    root, out_path, specs = sys.argv[1], sys.argv[2], sys.argv[3:]
    cache = {}
    chunks = [f"/* Generated by helperapp/tests/extract_decomp.py -- verbatim from the decomp. Do not edit. */\n"]
    for spec in specs:
        path, name = spec.split(":")
        if path not in cache:
            with open(f"{root}/{path}") as f:
                cache[path] = f.read()
        chunks.append(f"\n/* {path}: {name} */\n{extract(cache[path], name, path)}\n")
    with open(out_path, "w") as f:
        f.write("".join(chunks))


if __name__ == "__main__":
    main()
