#include "emerald_calc.h"

#include <string.h>

/* --- Item hold effects ----------------------------------------------------
 * Real GetItemHoldEffect()/GetItemHoldEffectParam() (src/item.c) just index
 * gItems[]; this table is that same data (holdEffect/holdEffectParam only)
 * generated by tools/gen_item_hold_effects.py, supplied at runtime rather
 * than linked in -- see EmeraldCalc_SetItemHoldEffects(). */
static const u8 *sItemHoldEffect = NULL;
static const u8 *sItemHoldEffectParam = NULL;
static u16 sItemCount = 0;

void EmeraldCalc_SetItemHoldEffects(const u8 *holdEffect, const u8 *holdEffectParam, u16 count)
{
    sItemHoldEffect = holdEffect;
    sItemHoldEffectParam = holdEffectParam;
    sItemCount = count;
}

u8 GetItemHoldEffect(u16 itemId)
{
    if (sItemHoldEffect == NULL || itemId >= sItemCount)
        return HOLD_EFFECT_NONE;
    return sItemHoldEffect[itemId];
}

u8 GetItemHoldEffectParam(u16 itemId)
{
    if (sItemHoldEffectParam == NULL || itemId >= sItemCount)
        return 0;
    return sItemHoldEffectParam[itemId];
}

void BattleState_Init(struct BattleState *s)
{
    int i, j;

    memset(s, 0, sizeof(*s));
    s->battlersCount = 2;
    for (i = 0; i < MAX_BATTLERS_COUNT; i++) {
        s->battlerPositions[i] = (u8)i;
        for (j = 0; j < NUM_BATTLE_STATS; j++)
            s->battleMons[i].statStages[j] = DEFAULT_STAT_STAGE;
    }
}
