#include "emerald_calc.h"

#include <string.h>

/* --- Item hold effects ----------------------------------------------------
 * Real GetItemHoldEffect()/GetItemHoldEffectParam() (src/item.c) just index
 * gItems[]; this table is that same data (holdEffect/holdEffectParam only)
 * generated by tools/gen_item_hold_effects.py, supplied at runtime rather
 * than linked in -- see EmeraldCalc_SetItemHoldEffects(). */
static const u8 *sItemHoldEffect = NULL;
static const u8 *sItemHoldEffectParam = NULL;
static u16 sItemCount = 0;

void EmeraldCalc_SetItemHoldEffects(const u8 *holdEffect, const u8 *holdEffectParam, u16 count)
{
    sItemHoldEffect = holdEffect;
    sItemHoldEffectParam = holdEffectParam;
    sItemCount = count;
}

u8 GetItemHoldEffect(u16 itemId)
{
    if (sItemHoldEffect == NULL || itemId >= sItemCount)
        return HOLD_EFFECT_NONE;
    return sItemHoldEffect[itemId];
}

u8 GetItemHoldEffectParam(u16 itemId)
{
    if (sItemHoldEffectParam == NULL || itemId >= sItemCount)
        return 0;
    return sItemHoldEffectParam[itemId];
}

EmeraldCalcFieldConditions EmeraldCalc_DefaultField(void)
{
    EmeraldCalcFieldConditions field;
    memset(&field, 0, sizeof(field));
    return field;
}
