# tools/gen_display_names.py
#
# The GUI needs Pokemon and move *names*, not raw ids (see the request that
# added the redesigned battler-column layout). Names live in
# src/data/text/species_names.h / src/data/text/move_names.h as
# `[SPECIES_X] = _("NAME")` / `[MOVE_X] = _("NAME")` designated
# initializers -- plain ASCII inside the source `.h` files themselves (the
# custom charmap in charmap.txt only matters once this is compiled into the
# ROM; reading the .h text directly needs no decoding).
#
#   python3 tools/gen_display_names.py > helperapp/config/display_names_us_rev0.json
import json
import re
import sys

SPECIES_CONST_H = "include/constants/species.h"
MOVES_CONST_H = "include/constants/moves.h"
ABILITIES_CONST_H = "include/constants/abilities.h"
POKEMON_CONST_H = "include/constants/pokemon.h"  # TYPE_*, NUMBER_OF_MON_TYPES
SPECIES_NAMES_H = "src/data/text/species_names.h"
MOVE_NAMES_H = "src/data/text/move_names.h"
ABILITY_NAMES_H = "src/data/text/abilities.h"  # also has description strings; harmless, see extract_names()
TYPE_NAMES_H = "src/battle_main.c"  # gTypeNames[] lives inline in this .c file, not a data/text header

DEFINE_NUM_RE = re.compile(r"^\s*#define\s+(\w+)\s+(\d+)\s*$")
DEFINE_ALIAS_RE = re.compile(r"^\s*#define\s+(\w+)\s+(\w+)\s*$")
ENTRY_RE = re.compile(r'\[(\w+)\]\s*=\s*_\("((?:[^"\\]|\\.)*)"\)')


def parse_defines(path):
    """Numeric #defines, plus single-level aliases (#define A B where B is
    itself a numeric #define -- e.g. NUM_SPECIES -> SPECIES_EGG)."""
    out = {}
    aliases = []
    with open(path) as f:
        for line in f:
            m = DEFINE_NUM_RE.match(line)
            if m:
                out[m.group(1)] = int(m.group(2))
                continue
            m = DEFINE_ALIAS_RE.match(line)
            if m:
                aliases.append((m.group(1), m.group(2)))
    for name, target in aliases:
        if target in out and name not in out:
            out[name] = out[target]
    return out


def extract_names(data_path, const_map, count):
    with open(data_path) as f:
        text = f.read()

    names = [""] * count
    unresolved = set()
    for m in ENTRY_RE.finditer(text):
        const_name, value = m.group(1), m.group(2)
        if const_name not in const_map:
            unresolved.add(const_name)
            continue
        idx = const_map[const_name]
        if idx < count:
            names[idx] = value
    return names, unresolved


def main():
    species_defines = parse_defines(SPECIES_CONST_H)
    num_species = species_defines["NUM_SPECIES"] + 1  # +1: NUM_SPECIES is the last valid id (SPECIES_EGG), not a count
    species_ids = {k: v for k, v in species_defines.items() if k.startswith("SPECIES_")}

    moves_defines = parse_defines(MOVES_CONST_H)
    moves_count = moves_defines["MOVES_COUNT"]
    move_ids = {k: v for k, v in moves_defines.items() if k.startswith("MOVE_")}

    abilities_defines = parse_defines(ABILITIES_CONST_H)
    abilities_count = abilities_defines["ABILITIES_COUNT"]
    ability_ids = {k: v for k, v in abilities_defines.items() if k.startswith("ABILITY_")}

    pokemon_defines = parse_defines(POKEMON_CONST_H)
    num_types = pokemon_defines["NUMBER_OF_MON_TYPES"]
    type_ids = {k: v for k, v in pokemon_defines.items() if k.startswith("TYPE_")}

    species_names, species_unresolved = extract_names(SPECIES_NAMES_H, species_ids, num_species)
    move_names, move_unresolved = extract_names(MOVE_NAMES_H, move_ids, moves_count)
    ability_names, ability_unresolved = extract_names(ABILITY_NAMES_H, ability_ids, abilities_count)
    type_names, type_unresolved = extract_names(TYPE_NAMES_H, type_ids, num_types)

    for label, const_h, unresolved in (
        ("species", SPECIES_CONST_H, species_unresolved),
        ("move", MOVES_CONST_H, move_unresolved),
        ("ability", ABILITIES_CONST_H, ability_unresolved),
        ("type", POKEMON_CONST_H, type_unresolved),
    ):
        if unresolved:
            print(f"WARNING: {label} names not resolvable via {const_h}: "
                  f"{sorted(unresolved)}", file=sys.stderr)

    out = {
        "_comment": (
            f"Generated by tools/gen_display_names.py from {SPECIES_NAMES_H}, "
            f"{MOVE_NAMES_H}, {ABILITY_NAMES_H} and {TYPE_NAMES_H}. "
            "Index == species id / move id / ability id / TYPE_* id."
        ),
        "species": species_names,
        "moves": move_names,
        "abilities": ability_names,
        "types": type_names,
    }
    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
