# tools/gen_item_hold_effects.py
#
# CODE_PLAN.md Phase 5.1: "port, do not reimplement." CalculateBaseDamage()
# (src/pokemon.c) reads each Pokemon's held item's hold-effect via
# GetItemHoldEffect()/GetItemHoldEffectParam(), which just index into
# gItems[] (src/data/items.h). That table also carries item names,
# description text, and ItemUseFunc function pointers we have no use for
# and can't link against outside the ROM build, so rather than pull the
# whole table in, this extracts only the two fields the damage calc
# actually reads -- reproducibly, from the decomp's own data, not
# hand-transcribed.
#
#   python3 tools/gen_item_hold_effects.py \
#       > helperapp/config/item_hold_effects_us_rev0.json
import json
import re
import sys

ITEMS_CONST_H = "include/constants/items.h"
HOLD_EFFECTS_CONST_H = "include/constants/hold_effects.h"
ITEMS_DATA_H = "src/data/items.h"

DEFINE_RE = re.compile(r"^\s*#define\s+(\w+)\s+(\d+)\s*$")


def parse_defines(path):
    out = {}
    with open(path) as f:
        for line in f:
            m = DEFINE_RE.match(line)
            if m:
                out[m.group(1)] = int(m.group(2))
    return out


def main():
    all_defines = parse_defines(ITEMS_CONST_H)
    items_count = all_defines["ITEMS_COUNT"]
    # Only ITEM_* names are item ids -- items.h also defines unrelated
    # constants (MAX_PC_ITEM_CAPACITY, pocket ids, ...) that share the same
    # "#define NAME NUMBER" shape and would otherwise pollute this map.
    item_ids = {k: v for k, v in all_defines.items() if k.startswith("ITEM_")}
    hold_effect_ids = parse_defines(HOLD_EFFECTS_CONST_H)

    with open(ITEMS_DATA_H) as f:
        text = f.read()

    # Matches one `[ITEM_X] = { ... }` designated-initializer block. Item
    # struct fields are flat (no nested braces), so a non-greedy match up
    # to the next `}` is exact.
    block_re = re.compile(r"\[(\w+)\]\s*=\s*\{(.*?)\n\s*\}", re.DOTALL)

    hold_effect = [0] * items_count       # HOLD_EFFECT_NONE default
    hold_effect_param = [0] * items_count  # 0 default, matches C's implicit

    missing_item_ids = set()
    unknown_hold_effects = set()

    for m in block_re.finditer(text):
        item_name, body = m.group(1), m.group(2)
        if item_name not in item_ids:
            missing_item_ids.add(item_name)
            continue
        idx = item_ids[item_name]

        he_m = re.search(r"\.holdEffect\s*=\s*(\w+)", body)
        if he_m:
            he_name = he_m.group(1)
            if he_name not in hold_effect_ids:
                unknown_hold_effects.add(he_name)
            else:
                hold_effect[idx] = hold_effect_ids[he_name]

        hep_m = re.search(r"\.holdEffectParam\s*=\s*(\d+)", body)
        if hep_m:
            hold_effect_param[idx] = int(hep_m.group(1))

    if missing_item_ids:
        print(f"WARNING: item names in {ITEMS_DATA_H} not found in "
              f"{ITEMS_CONST_H}: {sorted(missing_item_ids)}", file=sys.stderr)
    if unknown_hold_effects:
        print(f"WARNING: unrecognized HOLD_EFFECT_* names: "
              f"{sorted(unknown_hold_effects)}", file=sys.stderr)

    out = {
        "_comment": (
            f"Generated by tools/gen_item_hold_effects.py from {ITEMS_DATA_H}. "
            "Index == item id (see include/constants/items.h). Values are "
            "the numeric HOLD_EFFECT_* id (include/constants/hold_effects.h) "
            "and its param, exactly as GetItemHoldEffect()/"
            "GetItemHoldEffectParam() (src/item.c) would return them."
        ),
        "itemsCount": items_count,
        "holdEffect": hold_effect,
        "holdEffectParam": hold_effect_param,
    }
    json.dump(out, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
