#!/usr/bin/env python3
"""Collect the full set of generated/binary assets referenced by the
sources about to be compiled, from scaninc's per-source .d fragments (see
cmake/Assets.cmake), and emit them as an `ASSET_GOALS := ...` GNU Make
fragment for cmake/assets.mk to build.

scaninc (tools/scaninc/scaninc.cpp) writes each dependency it found for a
source — every .incbin'd file, every INCGFX_* target (each paired with a
dynamically generated recipe using the right gbagfx arguments), and every
resolved #include — twice: once as space-separated prerequisites on the
object rule's first line, and once individually as a bare "path:" line
with no recipe ("dummy rules", so a stale target doesn't abort the
build). The second form is what this script parses: it is one dependency
path per line, trivially unambiguous, and already exactly the set scaninc
determined this build needs — no extension whitelist to keep in sync with
gbagfx/rsfont's supported conversions (missing one silently breaks
whichever asset type it covers; see e.g. the .fwjpnfont font format,
which isn't handled by any generic pattern rule at all and depends
entirely on this dynamic-rule mechanism).

Requesting existing plain source/header files as Make goals here is
harmless (they have no rule and are already up to date); this
deliberately does not try to distinguish them from real build outputs.

Usage: collect_asset_goals.py DEPSCAN_DIR OUTPUT_MK
"""
import re
import sys
from pathlib import Path

DUMMY_RULE_RE = re.compile(r"^(\S+):$")


def extract_goals(text: str) -> set:
    goals = set()
    for line in text.splitlines():
        m = DUMMY_RULE_RE.match(line)
        if m:
            goals.add(m.group(1))
    return goals


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1

    depscan_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    goals = set()
    for d_file in depscan_dir.rglob("*.d"):
        goals |= extract_goals(d_file.read_text())

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write("# Auto-generated by cmake/collect_asset_goals.py. Do not edit.\n")
        f.write("ASSET_GOALS :=")
        for goal in sorted(goals):
            f.write(f" \\\n\t{goal}")
        f.write("\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
